### ISSUE TITLE
Request is sent but the returns error saying canceled.

### ISSUE THREAD

**Issue by NikosEfthias** [sagebind/chttp#30]
I am using twilio sms api and sending requests just fine on my Mac. But on ubuntu the request is sent and I receive the sms however the chttp always return an `Err` saying `canceled : unknown error`
<img width="600" alt="image" src="https://user-images.githubusercontent.com/9097437/59212333-c4983c80-8bba-11e9-9732-9648252ea9fa.png">

**Comment by sagebind** [comment]
Thanks for submitting a bug report! Since this is platform dependent, I'm guessing it has to do with a difference in version of libcurl being used under the hood. Could you send me what the output is of the following example program on both your Mac and Ubuntu machines? (Using the same version of `chttp` your project is using.)

```rust
fn main() {
    println!("version: {}", chttp::version());
}
```

That would be a big help! If it does turn out to be a difference between versions, I can try running against the exact version you are using in order to troubleshoot.

Upstream it is now possible to build a bundled curl always instead of linking to the system curl. I will add a crate feature to enable that and you can try it to see if it fixes the problem once I add it.

**Comment by NikosEfthias** [comment]
failing http version is `chttp/0.4.2 libcurl/7.58.0 OpenSSL/1.0.2n zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 l
ibrtmp/2.3`

and the successful one is `chttp/0.4.2 libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1`

**Comment by sagebind** [comment]
In addition, it would be a great help to me if you could include the trace logs from chttp when the error occurs. If you don't already have logging set up, you can do so with the [`env_logger`](https://docs.rs/env_logger) crate and then running your program with the `RUST_LOG` environment variable set to `chttp=trace`. Be sure to remove any sensitive details (like auth headers, etc) from the log first!

**Comment by sagebind** [comment]
@NikosEfthias I've just released [version 0.4.3](https://github.com/sagebind/chttp/releases/tag/0.4.3) which uses a bundled, tested version of libcurl by default instead of defaulting to whatever version of libcurl is available on the target system. This should workaround the issue until I can find the actual bug between chttp 0.4.2 and libcurl 7.58.0 interacting. Please give it a spin on your Ubuntu machine and let me know if it fixes the problem.

**Comment by NikosEfthias** [comment]
thanks im trying it now

**Comment by sagebind** [comment]
I created a similar environment to yours using Docker, but couldn't reproduce the error. Here's the Dockerfile:

```
FROM ubuntu:bionic

RUN apt update && \
    apt install -y build-essential curl git libcurl4 libcurl4-openssl-dev libssl-dev pkg-config && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

RUN git clone https://github.com/sagebind/chttp.git && \
    cd chttp && \
    git checkout 0.4.2 && \
    echo 'fn main(){println!("version: {}", chttp::version())}' > examples/version.rs && \
    cargo run --example version && \
    cargo run --example simple
```

This only verified that a simple `GET` request works using a similar combination of library versions. What kind of HTTP request are you making? The bug might be triggered by certain characteristics of your requests.

Based on the error message, I think what is happening is the agent thread is panicking and then dropping the request (the agent thread is a background thread managed by a `Client` instance that performs requests on your behalf). `Canceled` in this case means that the agent thread abandoned your request. Getting those trace logs might help a lot to identify why the agent thread might be panicking.

**Comment by NikosEfthias** [comment]
I had a chance to try on my Ubuntu machine today and I'm still getting cancelled unknown error on Ubuntu

**Comment by sagebind** [comment]
I'm sorry to hear that. Since I haven't been able to reproduce yet, it could be one of two things:

1. Something unique in your environment or program that chttp doesn't handle well, or
2. Some characteristic in the requests you are making that triggers a bug in chttp.

To eliminate the first possibility, please run the following program on your Ubuntu machine and post the output here: https://github.com/sagebind/chttp-issue-30/tree/4e02703de29fe7b882db9a1705b90740b82dc8fd

**Comment by NikosEfthias** [comment]
I am trying to test it now. I am on the go for a week already and I dont have a stable connection always. For the last 40 minutes im trying to compile psl for instance :)

**Comment by sagebind** [comment]
Yeah psl is a bit of a nuisance lately, I think a recent release made it worse. I created a separate issue for that here: https://github.com/sagebind/chttp/issues/31

**Comment by NikosEfthias** [comment]
`docker run -ti --rm -v (pwd):/app -w /app rust cargo build --release && strip -s target/release/<mybin>` this is how I build my code btw

**Comment by NikosEfthias** [comment]
Finaly I could run the program on my ubuntu machine ![here](https://transfer.sh/C1cf1/chttp.logs) are the logs

**Comment by NikosEfthias** [comment]
the last line also says the error is cancelled and it should have never happened I guess this is what I am having

**Comment by sagebind** [comment]
Yep, exactly right. This is the log line I was looking for:

```
[2019-06-13T21:15:36Z ERROR chttp::internal::request] request canceled by agent; this should never happen!
```

This does help me narrow down where the problem is occurring, I will continue to investigate.

**Comment by sagebind** [comment]
Good news; I've managed to reproduce the error you are seeing! By building in the manner you described, then running inside a container configured to be similar to your environment, I also get a `Canceled` error. I should be able to find the bug now. I might even get it fixed this evening!

**Comment by NikosEfthias** [comment]
actually for now until its fixed I can just stop handling the response because I really only care about the request being sent at this point of my app and after the fix I can put the response handling back.

**Comment by sagebind** [comment]
It looks like the crash doesn't happen in debug mode; for me anyway at least.

**Comment by NikosEfthias** [comment]
oh that's cool too

**Comment by NikosEfthias** [comment]
so until the fix I guess I can  deploy a debug build

**Comment by sagebind** [comment]
I may have found the issue. I think it is a result of a misuse of `debug_assert!`, which does not run the statement at all when compiled with release optimizations. This would be fine, except that I made a recent mistake and included a critical piece of code _inside_ the assert, which means it is never run in release mode. :man_facepalming: I sure feel foolish now!

In addition to publishing a fix for this ASAP, I will also start running example programs compiled in release mode as part of automated builds to ensure that this does not happen again.

**Comment by sagebind** [comment]
This should now be fixed in version 0.4.4!

**Comment by NikosEfthias** [comment]
cool first thing i will be testing with the project we used earlier to find the bug. I really appreciate the work you put on this and you were friendly and nice from the beginning
